# Generated by Django 3.1.2 on 2020-10-11 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Статья доходов')),
            ],
            options={
                'verbose_name_plural': 'Доходы',
            },
        ),
        migrations.CreateModel(
            name='SpendCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
            ],
            options={
                'verbose_name_plural': 'Категории расходов',
            },
        ),
        migrations.CreateModel(
            name='SpendArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название статьи расходов')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spends.spendcategory')),
            ],
            options={
                'verbose_name_plural': 'Статьи расходов',
            },
        ),
    ]
