# Generated by Django 3.1.2 on 2020-10-19 10:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spends', '0004_auto_20201019_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeoperation',
            name='income_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 19, 10, 47, 42, 605688, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='spendoperation',
            name='spend_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 19, 10, 47, 42, 606690, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
