# Generated by Django 3.1.2 on 2020-10-11 14:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0002_account_incomeoperation_spendoperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeoperation',
            name='income_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 11, 14, 14, 39, 582328, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='spendoperation',
            name='spend_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 11, 14, 14, 39, 583324, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
