# Generated by Django 3.1.2 on 2020-10-27 14:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0006_auto_20201020_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeoperation',
            name='comment_for_income_operation',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='spendoperation',
            name='comment_for_spend_operation',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='incomeoperation',
            name='income_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 27, 14, 26, 5, 587159, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='spendoperation',
            name='spend_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 27, 14, 26, 5, 588160, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
