# Generated by Django 3.1.2 on 2020-10-27 16:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0007_auto_20201027_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeoperation',
            name='comment_for_income_operation',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='incomeoperation',
            name='income_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 27, 16, 46, 58, 995767, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='spendoperation',
            name='comment_for_spend_operation',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='spendoperation',
            name='spend_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 27, 16, 46, 58, 996765, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
