# Generated by Django 3.1.2 on 2020-10-27 19:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0009_auto_20201027_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeoperation',
            name='income_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 19, 13, 18, 570009, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='spendoperation',
            name='spend_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 27, 19, 13, 18, 571006, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
