# Generated by Django 3.1.2 on 2020-11-04 09:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0011_auto_20201027_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeoperation',
            name='income_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incomes.income', verbose_name='Статья дохода'),
        ),
        migrations.AlterField(
            model_name='incomeoperation',
            name='income_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 4, 9, 51, 38, 515214, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='spendoperation',
            name='spend_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incomes.spendarticle', verbose_name='Статья расхода'),
        ),
        migrations.AlterField(
            model_name='spendoperation',
            name='spend_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 4, 9, 51, 38, 515214, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
