# Generated by Django 3.1.2 on 2020-11-07 10:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0012_auto_20201104_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeoperation',
            name='income_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 10, 10, 6, 645642, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='spendoperation',
            name='spend_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 10, 10, 6, 646642, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
